[tool.pylint.master]
job = 0 # 默認多進程
suggestion-mode = "yes" # 顯示建議

[tool.pylint.format]
max-line-length = 120

[tool.pylint.basic]
argument-naming-style = "any" # 參數
attr-naming-style = "any" # 屬性
function-naming-style = "any" # 函數
method-naming-style = "any" # 方法
variable-naming-style = "any" # 變數

[tool.pylint.message_control]
disable = [
    "missing-docstring",
    "logging-fstring-interpolation", # 在log使用f-string
    "no-member",
 ]

[tool.black]
line-length = 120

[tool.isort]
line_length = 120
use_parentheses = true # 是否要括號
include_trailing_comma = true # 在換行的地方加逗號
multi_line_output = 3
src_paths = ["main"] # 哪些目錄要套用
